### ISSUE TITLE
Uzbek translation is missing

### ISSUE THREAD

**Issue by smekosh** [bbgvisualjournalist/circumventing-censorship#1]
The Uzbek translation needs to be pulled into the repository:
https://projects.voanews.com/circumvention/uzbek/

**Comment by bbgvisualjournalist** [comment]
Added the [Uzbek translation](https://github.com/bbgvisualjournalist/circumvention/commit/b194c11cf57ec9b7be78e92313676edc958dd678) and inserted it into the dropdown translation nav.
